[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"


[features]
resolution = true
skip-lint = false

[programs.devnet]
quant = "GfHdK9T6kBwS55D9pv97CbNE9PdP4kpASxMipM7gWSKa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rachitsharma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
